### ISSUE TITLE
Maxes out at 10

### ISSUE THREAD

**Issue by codysherman** [pgrimaud/lametric-cryptocurrencies#10]
Can't seem to get the app to display the 11th currency code or further.

**Comment by pgrimaud** [comment]
Yes, Lametric only allows 20 frames per app. 😢 

So if you enabled the option "Show percent change", you will have 20 frames with the first 10 cryptos. 
`(1 frame for price + 1 frame for change) * 10 = 20`

That's why the 11th is not shown.

**Comment by codysherman** [comment]
Gotcha noted. Kinda relates to the other issue I was waiting to open, as another solution would be to skip the name pages, but that requires some missing icons.

Thanks for the quick response. I'll open a new issue separately to help keep everything organized.

**Comment by pgrimaud** [comment]
Yes, perfect. thanks :)

**Comment by codysherman** [comment]
Just adding here for other Lametric n00bs like me, there is a very simple workaround for the limitation. If you just long press the app's icon, you can "duplicate" the app, enabling another 10 crypto slots, etc.

I just got my Lametric yesterday, so didn't realize that was an option, sorry!
