### ISSUE TITLE
Codes with duplicate coins problem

### ISSUE THREAD

**Issue by codysherman** [pgrimaud/lametric-cryptocurrencies#11]
When attempting to add the Uniswap coin (UNI), the app is displaying a different coin with the UNI code. Can the code be adjusted to use the higher market cap coin when there are multiple results? Or some way to specify exact coins past just the abbreviation (aka typing out the full "uniswap")?

It does show the correct Uniswap icon, but the price is for a different coin with UNI as abbreviation.

**Comment by pgrimaud** [comment]
Hey @codysherman 

I just fixed it. Tell me if it's working on your Lametric 😄

**Comment by codysherman** [comment]
Confirmed it's working, thanks a ton @pgrimaud
