### ISSUE TITLE
Missing Crypto Icons

### ISSUE THREAD

**Issue by codysherman** [pgrimaud/lametric-cryptocurrencies#13]
Here is a list of crypto icons that I've noticed are missing:

- Bitcoin Cash (BCH)
- AAVE
- Algorand (ALGO)
- NuCypher (NU)
- SUSHI
- Cosmos (ATOM)
- The Graph (GRT)
- REN

Finally, there is also MATIC, but today it was announced they are rebranding to Polygon, so... kinda don't even know what to do about this one.

**Comment by pgrimaud** [comment]
@codysherman I added the icons except for MATIC

**Comment by codysherman** [comment]
Killer dude, you rock!

Is there a repo of all the icons somewhere you grab them from? Happy to do that for you and open a PR next time if I want another icon added.

**Comment by pgrimaud** [comment]
Sure, it could be awesome !

First, you can create a free account on : https://developer.lametric.com/.

Then, create an app (without releasing it) and add a app icon : 

![image](https://user-images.githubusercontent.com/1866496/107656545-92d75300-6c84-11eb-9f86-be8fa881f6b6.png)

Finally, design you icon :
![image](https://user-images.githubusercontent.com/1866496/107656629-a5ea2300-6c84-11eb-8ab1-8ff56c67d544.png)

You will get an icon id and you could add it here : https://github.com/pgrimaud/lametric-cryptocurrencies/blob/master/src/Crypto/Helper/IconHelper.php

**Comment by codysherman** [comment]
Wait are you manually drawing each icon? I just tried to create one, I thought I could upload an image and it would auto-convert, then I could touch it up.
