### ISSUE TITLE
Cents should always show hundredth place

### ISSUE THREAD

**Issue by codysherman** [pgrimaud/lametric-cryptocurrencies#14]
Prices that end in a multiple of 10 cents should show the ending 0.

Example:
"123.4" should display as "123.40"

**Comment by pgrimaud** [comment]
How prices are in a multiple of 10 cents show the ending 0. Only for the price between $100 et $999, to avoid the price being too long on screen size.

**Comment by codysherman** [comment]
Not sure I described by issue correctly. I understand removing the cents for larger numbers, but when cents are shown, it should always be 2 digits:
❌1.2
✅1.20

**Comment by pgrimaud** [comment]
What if crypto worth 0.001$?

i.e. : https://coinmarketcap.com/currencies/bittorrent/

**Comment by codysherman** [comment]
I'm not saying to crop, $0.001 is fine. I was just saying $4.1 looks really weird. It's definitely an edge case to code for. I understand if it isn't worth fixing.

**Comment by pgrimaud** [comment]
Alright, gotcha! It's fixed.

Tell me if you got a weird rounding price in the next days.

**Comment by codysherman** [comment]
Thanks! Will keep an eye on it!
