### ISSUE TITLE
Dollar sign placement options

### ISSUE THREAD

**Issue by codysherman** [pgrimaud/lametric-cryptocurrencies#15]
Requesting an option to show the dollar sign "$" before the number rather than after, as well as an option to just not include it at all.

Options:
1000$ (Current)
$1000
1000

**Comment by pgrimaud** [comment]
@codysherman If you update the app to version 9, you will find a new option "Dollar sign position".

You can choose to set the dollar sign : 
- before price
- after price
- hide it

**Comment by codysherman** [comment]
Perfection.
