### ISSUE TITLE
GRT coin pulling wrong coin

### ISSUE THREAD

**Issue by codysherman** [pgrimaud/lametric-cryptocurrencies#17]
GRT is not pulling The Graph coin, it's instead pulling "Golden Ratio Token"'s price.

https://coinmarketcap.com/currencies/the-graph/

**Comment by pgrimaud** [comment]
Good catch, it's fixed.

Fucking cryptos with same symbol, I must find a way to handle it easily...

**Comment by codysherman** [comment]
Thanks! Yeah, is the API supplying each coin's Market Cap? You could just pick the one with the highest Market Cap if there are multiple results.

**Comment by pgrimaud** [comment]
@codysherman I updated it. Now, it will return only the coin with the highest market cap 😉

**Comment by pgrimaud** [comment]
Seriously, who give a shit about https://coinmarketcap.com/currencies/golden-ratio-token/? 😂

**Comment by codysherman** [comment]
You rock dude, for real. Killing it. Sent you a tip on Paypal earlier, hope you got it!

**Comment by pgrimaud** [comment]
> Sent you a tip on Paypal earlier, hope you got it!

Gotcha, thank you SO MUCH! ❤️
