### ISSUE TITLE
Icon request: 1inch

### ISSUE THREAD

**Issue by codysherman** [pgrimaud/lametric-cryptocurrencies#18]
Requesting 1inch coin icon. Tried to create one myself but artistic talent is lacking. Is there a way to import an image as a guide? I've you've been drawing all of the existing icons I'm extremely impressed.

https://coinmarketcap.com/currencies/1inch/

**Comment by pgrimaud** [comment]
I don't find a way to import image... Yeah I designed it manually haha.

I added 1INCH icon, I'm not happy with the result... This logo is hard to design. Tell me what you think about it. 😄
