### ISSUE TITLE
Currencies conversion request (EUR, GBP , BTC , ETH) 

### ISSUE THREAD

**Issue by m0s4ik** [pgrimaud/lametric-cryptocurrencies#19]
It would be possible to have an option to select the reference currency in addition to the USD?

Example:
https://web-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?convert=EUR&cryptocurrency_type=all&limit=4999
https://web-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?convert=GBP &cryptocurrency_type=all&limit=4999
https://web-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?convert=BTC&cryptocurrency_type=all&limit=4999
https://web-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?convert=ETH&cryptocurrency_type=all&limit=4999

Regards

**Comment by pgrimaud** [comment]
Hello, I though about it when someone ask me the same feature on my LaMetric real-time Bitcoin app. (https://github.com/pgrimaud/lametric-bitcoin-realtime/commit/cca281d14825cafd5085debac7c30f5740516f3b)

Just one quick question, only physical currencies (USD/GBP/etc.) or physical and crypto (BTC/ETH/others)?

**Comment by m0s4ik** [comment]
I would like the conversion into EUR but the equivalent in BTC could also be useful. :)

**Comment by pgrimaud** [comment]
If you update the app on your LaMetric to version 10, you will find an option to choose the currency display on the app.

Tell me if it's working for you.

**Comment by m0s4ik** [comment]
Awesom it works! 

Thank you so much! :)

**Comment by pgrimaud** [comment]
You're welcome. If you like this app, please considering to like this repository. ⭐ 🙏
