### ISSUE TITLE
Configurable list

### ISSUE THREAD

**Issue by asebak** [pgrimaud/lametric-cryptocurrencies#2]
Hey man, this is great work.  It would be nice to have the option to select which currencies you want like a multi select.  There's already another crpyto app that does it but only has like 10 choices.  I like this because it has a huge range.  Also would be nice to use the icon for the coin if possible.

**Comment by pgrimaud** [comment]
Hi @asebak ,

Which application did it?

Yeah, It could be nice to add a multiselect, but it may be hard because the app can manage more than 1100 currency. Let's see if I can find a trick :)

**Comment by asebak** [comment]
This was the app I was taking about:

https://apps.lametric.com/apps/cryptoticker/4795

I am not sure how they do this. The lametric SDK is very limited and not enough examples.
