### ISSUE TITLE
No more than 7 currencies?

### ISSUE THREAD

**Issue by dswihart** [pgrimaud/lametric-cryptocurrencies#24]
The application won’t load more than 7 currencies, before cycling back to the beginning.

**Comment by pgrimaud** [comment]
Hello @dswihart 

Yes, LaMetric only allows 20 frames per app. 😢

So if you enabled the options "Show crypto names" and "Show daily change" you will have 21 frames with the first 7 cryptos.
(1 frame for name + 1 frame for price + 1 frame for change) * 10 = 21

That's why the 8h is not shown.

**Comment by dswihart** [comment]
Damnit. I figured it was something t like that.  I appreciate the app either way.
