### ISSUE TITLE
Rate Limiter

### ISSUE THREAD

**Issue by YanDevDe** [pgrimaud/lametric-cryptocurrencies#37]
Hello! Great app, as always! :)

I'm currently facing the issue that I'm always getting the error "Rate Limiter Reached, please wait a bit". 

Just letting ya know! :)

Thanks,

Yan

**Comment by pgrimaud** [comment]
Damn, I just updated the app. Hope it will fixed it. We have to wait a couple of minutes to get back to normal.

**Comment by YanDevDe** [comment]
Gotcha, will let you know in one hour! Thank you so much for the quick reply and fix lol!

**Comment by YanDevDe** [comment]
Looks like it worked! :) Fantastic - Thank you @pgrimaud!

**Comment by pgrimaud** [comment]
Hope it will work for a long times 😥

**Comment by YanDevDe** [comment]
May want to checkout at coingecko.com - they have much friendlier API & Rate Limiter! Just an idea 😄

**Comment by pgrimaud** [comment]
Good idea, I will add an option into the app to select data provider (CoinMarketCap or CoinGecko). 

It will decrease API calls to CMC and balance into the two data providers. 

What do you think about it?

**Comment by YanDevDe** [comment]
Actually that's an interesting idea! I'm not quite sure how much work it would be - but selecting data providers individually by cryptocurrency  could be interesting too? 

I only know that I didn't had issue by using CoinGecko for our own software. It's also being called per users. But with CoinMarketCap they were way more stricter so I just gave up on them lol.

**Comment by pgrimaud** [comment]
IMHO, data providers will be select for all currencies selected on the app.

**Comment by pgrimaud** [comment]
We switched to Coingecko, so no more rate limit 🎉
