### ISSUE TITLE
Positive change percentage - red down arrow displayed

### ISSUE THREAD

**Issue by jstiops** [pgrimaud/lametric-cryptocurrencies#40]
Thanks for the app! love it.

i'm seeing an issue with the percentage change feature at some times. positive percentages (+1.73% for example) gets displayed with the red down arrow.

Also noticed the opposite by the way. Up arrow with negative change

![3537AA25-824F-461E-952E-B662C053D811](https://user-images.githubusercontent.com/1699208/137262977-013cec4c-c2c1-4afd-9c3d-aa7f4e812f31.jpeg)

**Comment by cmelius** [comment]
I always thought that percentage stands for 24h changes and the arrow is the direction, the currency currently moves.
And if I observe, this totally seems possible. 
Is it not meant to be this way?

**Comment by pgrimaud** [comment]
Hey,

Sorry about the delay. I just understand where the issue comes.
I used "GIF" as arrow up and down, and I seems there's an issue with it.

So I changed to simple icons (instead of GIF). It fixed the problem on my LaMetric.

Someone could confirm?

**Comment by pgrimaud** [comment]
My fix changed nothing 😢 

It seems to be a known bug reported to LaMetric. https://help.lametric.com/support/discussions/topics/6000065055?page=1
I can't fixed it yet, because it doesn't come from the app, but from the firmware.

Wait for LaMetric to fixed it. I just send a message to their support team.

**Comment by cmelius** [comment]
It didn't fix it for me. Running 2.2.3 since mid March.today it still looks like this. 
![20220407_204858](https://user-images.githubusercontent.com/43573594/162275555-63ae96b5-0732-4575-9934-ec6bf3cd3d27.jpg)
