### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by cmelius** [pgrimaud/lametric-cryptocurrencies#49]
Just wanted to let you know: I only get "internal error" displayed on my lametric in cryptocurrencies for about 2 days now. 
Rebooted several times, that does not change anything.
Thanks and keep up the great work!

**Comment by billbazza** [comment]
I have the same issue. I thought it might be local DNS blocking access but I can find no such blocks

**Comment by Sab3rRid3r** [comment]
Same situation here ‚INTERNAL ERROR‘ for about a week I think.

**Comment by cmelius** [comment]
Update: it seems to work now!  Thanks for the fix
