### ISSUE TITLE
Data IS n'ont updating anymore

### ISSUE THREAD

**Issue by MetallianFR68** [pgrimaud/lametric-cryptocurrencies#5]
Hi,

All crypto data has stopped updating since August 13th

I tried rebooting the Lametric several times

Is there a problem with the data provider ?

**Comment by pgrimaud** [comment]
Hi @MetallianFR68,

Thanks for the issue. 
It wasn't a problem with the data provider but with the web server (more precisely the redis server) which doesn't refresh the data. 

I flush all keys from redis server and it works again. Can you confirm?

I will fix the app next week to to prevent this from happening again.

**Comment by MetallianFR68** [comment]
I can confirm it is working again.
Thanks for this very useful app !
