### ISSUE TITLE
Luka Currency

### ISSUE THREAD

**Issue by szirottir** [pgrimaud/lametric-cryptocurrencies#6]
Hey! im from Chile, i recently purchase my LaMetric, i love ur app, is amayzing! i was wondering if there is any chance for you to add the crypto "Luka"? You would help me a lot!

Thanks men! and keep up the good work!

here's the official page! https://www.cryptoluka.cl/

**Comment by pgrimaud** [comment]
Hi @szirottir ,

Unfortunately I can't add this crypto. My app is based on data from https://coinmarketcap.com/.
If this currency is added to CoinMarketCap, it will be available on this LaMetric App.

Best,

Pierre
